INFO 2025-03-12 16:20:51,426 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 16:26:10,379 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 16:28:01,844 autoreload Watching for file changes with StatReloader
WARNING 2025-03-13 16:28:13,954 log Not Found: /
WARNING 2025-03-13 16:28:13,955 basehttp "GET / HTTP/1.1" 404 2504
WARNING 2025-03-13 16:28:13,964 log Not Found: /
WARNING 2025-03-13 16:28:13,964 basehttp "GET / HTTP/1.1" 404 2504
WARNING 2025-03-13 16:28:14,017 log Not Found: /favicon.ico
WARNING 2025-03-13 16:28:14,018 basehttp "GET /favicon.ico HTTP/1.1" 404 2555
INFO 2025-03-13 16:28:23,926 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2025-03-13 16:28:23,948 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4178
INFO 2025-03-13 16:28:23,959 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-13 16:28:23,961 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-13 16:28:23,961 basehttp "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-03-13 16:28:23,963 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-13 16:28:23,963 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-13 16:28:23,964 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-13 16:28:23,964 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-13 16:34:41,389 autoreload D:\code\Soulwhisper\backend\soul_backend\admin.py changed, reloading.
INFO 2025-03-13 16:34:42,310 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 16:34:49,032 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 16:38:11,380 autoreload D:\code\Soulwhisper\backend\soul_backend\admin.py changed, reloading.
INFO 2025-03-13 16:38:12,202 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 16:39:14,125 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 16:39:14,797 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 16:40:46,502 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 16:40:47,183 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 16:42:21,377 autoreload D:\code\Soulwhisper\backend\soul_backend\__init__.py changed, reloading.
INFO 2025-03-13 16:42:21,808 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 17:04:52,885 autoreload D:\code\Soulwhisper\backend\soul_backend\account\models.py changed, reloading.
INFO 2025-03-13 17:04:54,000 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 20:09:02,810 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 20:21:52,322 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 20:23:29,604 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:32:06,309 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:32:54,262 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 21:32:55,669 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:34:44,095 autoreload D:\code\Soulwhisper\backend\soul_backend\__init__.py changed, reloading.
INFO 2025-03-13 21:34:45,088 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:35:39,192 autoreload D:\code\Soulwhisper\backend\soul_backend\__init__.py changed, reloading.
INFO 2025-03-13 21:35:39,917 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:39:41,759 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 21:39:42,401 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:40:05,044 autoreload D:\code\Soulwhisper\backend\soul_backend\account\models.py changed, reloading.
INFO 2025-03-13 21:40:05,383 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:42:00,907 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 21:42:01,577 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:44:12,087 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:45:30,812 autoreload D:\code\Soulwhisper\backend\soul_backend\chat\models.py changed, reloading.
INFO 2025-03-13 21:45:31,495 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:54:54,683 autoreload D:\code\Soulwhisper\backend\soul_backend\chat\models.py changed, reloading.
INFO 2025-03-13 21:54:55,369 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:57:56,869 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 21:57:57,553 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 21:58:53,707 autoreload D:\code\Soulwhisper\backend\soul_backend\account\migrations\__init__.py changed, reloading.
INFO 2025-03-13 21:58:54,375 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 22:07:59,370 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 22:08:00,058 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 22:09:14,485 autoreload D:\code\Soulwhisper\backend\soul_backend\__init__.py changed, reloading.
INFO 2025-03-13 22:09:15,224 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 22:09:29,393 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 22:10:41,564 autoreload D:\code\Soulwhisper\backend\soul_backend\account\models.py changed, reloading.
INFO 2025-03-13 22:10:41,703 autoreload D:\code\Soulwhisper\backend\soul_backend\account\models.py changed, reloading.
INFO 2025-03-13 22:10:42,323 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 22:10:42,462 autoreload Watching for file changes with StatReloader
WARNING 2025-03-13 22:10:46,773 log Not Found: /
WARNING 2025-03-13 22:10:46,773 basehttp "GET / HTTP/1.1" 404 2504
WARNING 2025-03-13 22:10:46,831 log Not Found: /favicon.ico
WARNING 2025-03-13 22:10:46,832 basehttp "GET /favicon.ico HTTP/1.1" 404 2555
INFO 2025-03-13 22:16:23,448 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 22:16:24,123 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 22:29:55,417 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 22:29:56,438 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 22:33:08,458 autoreload Watching for file changes with StatReloader
WARNING 2025-03-13 22:33:12,589 log Not Found: /
WARNING 2025-03-13 22:33:12,589 basehttp "GET / HTTP/1.1" 404 2504
INFO 2025-03-13 22:33:16,031 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2025-03-13 22:33:16,053 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2025-03-13 22:33:16,069 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-03-13 22:33:16,072 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-03-13 22:33:16,072 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-03-13 22:33:16,073 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-03-13 22:33:16,074 basehttp "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-03-13 22:33:16,075 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-03-13 22:33:16,075 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-03-13 22:33:30,367 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-03-13 22:33:30,381 basehttp "GET /admin/ HTTP/1.1" 200 5555
INFO 2025-03-13 22:33:30,665 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-03-13 22:33:30,665 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-03-13 22:33:30,666 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-03-13 23:03:32,450 autoreload D:\code\Soulwhisper\backend\soul_backend\diary\urls.py changed, reloading.
INFO 2025-03-13 23:03:33,107 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:04:13,373 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:06:05,924 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:06:06,224 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:06:54,391 autoreload D:\code\Soulwhisper\backend\apps\apps.py changed, reloading.
INFO 2025-03-13 23:06:54,761 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:14:32,824 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:14:33,108 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:16:27,791 autoreload D:\code\Soulwhisper\backend\apps\diary\apps.py changed, reloading.
INFO 2025-03-13 23:16:28,165 autoreload Watching for file changes with StatReloader
WARNING 2025-03-13 23:16:38,455 log Not Found: /
WARNING 2025-03-13 23:16:38,456 basehttp "GET / HTTP/1.1" 404 2504
INFO 2025-03-13 23:16:44,409 basehttp "GET /admin/ HTTP/1.1" 200 5555
INFO 2025-03-13 23:16:49,799 basehttp "GET /admin/ HTTP/1.1" 200 5555
INFO 2025-03-13 23:18:14,315 basehttp "GET /admin/ HTTP/1.1" 200 5555
WARNING 2025-03-13 23:18:18,906 log Not Found: /asr_view/
WARNING 2025-03-13 23:18:18,907 basehttp "GET /asr_view/ HTTP/1.1" 404 2549
WARNING 2025-03-13 23:18:33,555 log Not Found: /diary/asr_view/
WARNING 2025-03-13 23:18:33,555 basehttp "GET /diary/asr_view/ HTTP/1.1" 404 2567
INFO 2025-03-13 23:19:57,132 basehttp "GET /admin/ HTTP/1.1" 200 5555
WARNING 2025-03-13 23:20:07,213 log Not Found: /asr_view
WARNING 2025-03-13 23:20:07,213 basehttp "GET /asr_view HTTP/1.1" 404 2546
WARNING 2025-03-13 23:20:27,989 log Not Found: /diary/asr_view
WARNING 2025-03-13 23:20:27,989 basehttp "GET /diary/asr_view HTTP/1.1" 404 2564
WARNING 2025-03-13 23:20:43,020 log Not Found: /diary/asr_view/
WARNING 2025-03-13 23:20:43,020 basehttp "GET /diary/asr_view/ HTTP/1.1" 404 2567
INFO 2025-03-13 23:21:07,290 autoreload D:\code\Soulwhisper\backend\config\urls.py changed, reloading.
INFO 2025-03-13 23:21:08,070 autoreload Watching for file changes with StatReloader
WARNING 2025-03-13 23:21:11,408 log Method Not Allowed: /api/diary/asr_view/
WARNING 2025-03-13 23:21:11,408 basehttp "GET /api/diary/asr_view/ HTTP/1.1" 405 47
INFO 2025-03-13 23:21:53,844 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:21:54,643 autoreload Watching for file changes with StatReloader
WARNING 2025-03-13 23:23:03,546 log Method Not Allowed: /api/diary/emotion_view/
WARNING 2025-03-13 23:23:03,547 basehttp "GET /api/diary/emotion_view/ HTTP/1.1" 405 47
INFO 2025-03-13 23:26:40,700 autoreload D:\code\Soulwhisper\backend\apps\account\apps.py changed, reloading.
INFO 2025-03-13 23:26:41,429 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:33:11,845 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-13 23:33:12,776 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:33:21,995 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-13 23:33:22,702 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:34:24,365 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-13 23:34:24,712 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:34:39,063 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-13 23:34:39,807 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:35:04,823 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-13 23:35:05,494 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:35:48,785 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-13 23:35:49,507 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:36:17,292 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:39:00,646 basehttp "GET /admin/ HTTP/1.1" 200 5555
WARNING 2025-03-13 23:39:02,867 log Not Found: /diary/asr_view/
WARNING 2025-03-13 23:39:02,867 basehttp "GET /diary/asr_view/ HTTP/1.1" 404 2567
INFO 2025-03-13 23:43:24,291 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-13 23:43:25,004 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:46:09,116 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:46:09,432 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:47:46,783 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:48:22,554 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:48:22,833 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:48:24,944 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:48:41,389 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:48:41,470 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:48:41,733 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:48:41,822 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:48:50,998 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:48:51,780 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:48:52,023 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-13 23:48:52,815 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:49:25,521 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-13 23:49:25,734 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-13 23:49:26,268 autoreload Watching for file changes with StatReloader
INFO 2025-03-13 23:49:26,491 autoreload Watching for file changes with StatReloader
WARNING 2025-03-13 23:49:57,941 log Method Not Allowed: /api/account/register/
WARNING 2025-03-13 23:49:57,942 basehttp "GET /api/account/register/ HTTP/1.1" 405 40
WARNING 2025-03-13 23:50:07,928 log Bad Request: /api/account/register/
WARNING 2025-03-13 23:50:07,928 basehttp "POST /api/account/register/ HTTP/1.1" 400 76
ERROR 2025-03-13 23:50:21,536 log Internal Server Error: /api/account/login
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/account/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2025-03-13 23:50:21,537 basehttp "POST /api/account/login HTTP/1.1" 500 73632
WARNING 2025-03-13 23:50:27,300 log Bad Request: /api/account/login/
WARNING 2025-03-13 23:50:27,300 basehttp "POST /api/account/login/ HTTP/1.1" 400 76
INFO 2025-03-13 23:50:39,228 basehttp "POST /api/account/logout/ HTTP/1.1" 200 32
WARNING 2025-03-14 00:00:38,259 log Not Found: /api/account/
WARNING 2025-03-14 00:00:38,260 basehttp "POST /api/account/?email=user1@example.com&password=pbkdf2_sha256260000260000 HTTP/1.1" 404 3254
WARNING 2025-03-14 00:01:56,697 log Not Found: /api/account/
WARNING 2025-03-14 00:01:56,697 basehttp "POST /api/account/?email=user1@example.com&password=pbkdf2_sha256260000260000 HTTP/1.1" 404 3254
ERROR 2025-03-14 00:02:25,791 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:02:25,817 log Bad Request: /api/account/
WARNING 2025-03-14 00:02:25,817 basehttp "POST /api/account/ HTTP/1.1" 400 72290
ERROR 2025-03-14 00:03:20,040 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:03:20,056 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:03:20,056 basehttp "POST /api/account/register/ HTTP/1.1" 400 72486
ERROR 2025-03-14 00:03:35,334 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:03:35,347 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:03:35,348 basehttp "GET /api/account/register/ HTTP/1.1" 400 72479
ERROR 2025-03-14 00:04:06,348 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:04:06,361 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:04:06,361 basehttp "GET /api/account/register/ HTTP/1.1" 400 72559
ERROR 2025-03-14 00:04:15,015 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:04:15,030 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:04:15,031 basehttp "POST /api/account/register/ HTTP/1.1" 400 72566
WARNING 2025-03-14 00:07:05,406 log Method Not Allowed: /api/diary/emotion_view/
WARNING 2025-03-14 00:07:05,406 basehttp "GET /api/diary/emotion_view/ HTTP/1.1" 405 47
INFO 2025-03-14 00:07:08,782 basehttp "GET /admin/ HTTP/1.1" 200 5555
WARNING 2025-03-14 00:07:19,925 log Not Found: /api/register/
WARNING 2025-03-14 00:07:19,925 basehttp "GET /api/register/ HTTP/1.1" 404 2561
ERROR 2025-03-14 00:07:37,476 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\renderers.py", line 726, in render
    template = loader.get_template(self.template)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2025-03-14 00:07:37,478 basehttp "GET /api/account/register/ HTTP/1.1" 500 86399
ERROR 2025-03-14 00:08:49,913 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:08:49,926 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:08:49,926 basehttp "POST /api/account/register/ HTTP/1.1" 400 72486
ERROR 2025-03-14 00:10:26,535 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:10:26,549 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:10:26,550 basehttp "POST /api/account/register/ HTTP/1.1" 400 72486
INFO 2025-03-14 00:11:09,978 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:11:10,673 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:11:10,770 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:11:11,438 autoreload Watching for file changes with StatReloader
ERROR 2025-03-14 00:11:15,231 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:11:15,251 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:11:15,252 basehttp "POST /api/account/register/ HTTP/1.1" 400 72486
INFO 2025-03-14 00:11:30,209 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:11:30,930 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:11:31,019 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:11:31,676 autoreload Watching for file changes with StatReloader
ERROR 2025-03-14 00:11:40,827 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:11:40,849 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:11:40,850 basehttp "GET /api/account/register/ HTTP/1.1" 400 72480
ERROR 2025-03-14 00:12:21,493 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:12:21,507 log Bad Request: /api/account/login/
WARNING 2025-03-14 00:12:21,508 basehttp "GET /api/account/login/ HTTP/1.1" 400 72444
ERROR 2025-03-14 00:12:30,751 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:12:30,768 log Bad Request: /api/account/logout/
WARNING 2025-03-14 00:12:30,768 basehttp "GET /api/account/logout/ HTTP/1.1" 400 72456
ERROR 2025-03-14 00:12:55,818 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:12:55,830 log Bad Request: /api/account/logout
WARNING 2025-03-14 00:12:55,831 basehttp "GET /api/account/logout HTTP/1.1" 400 72350
ERROR 2025-03-14 00:13:30,434 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:13:30,448 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:13:30,448 basehttp "GET /api/account/register/ HTTP/1.1" 400 72480
ERROR 2025-03-14 00:13:34,105 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:13:34,119 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:13:34,119 basehttp "GET /api/account/register/ HTTP/1.1" 400 72480
ERROR 2025-03-14 00:13:37,160 exception Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'local.id.seewo.com:8000'. You may need to add 'local.id.seewo.com' to ALLOWED_HOSTS.
WARNING 2025-03-14 00:13:37,173 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:13:37,173 basehttp "POST /api/account/register/ HTTP/1.1" 400 72487
INFO 2025-03-14 00:15:23,077 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:15:23,325 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:15:23,866 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:15:24,094 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:15:29,018 basehttp "GET /admin/ HTTP/1.1" 200 5555
ERROR 2025-03-14 00:15:30,651 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\renderers.py", line 726, in render
    template = loader.get_template(self.template)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2025-03-14 00:15:30,653 basehttp "GET /api/account/register/ HTTP/1.1" 500 86428
ERROR 2025-03-14 00:15:31,593 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\renderers.py", line 726, in render
    template = loader.get_template(self.template)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2025-03-14 00:15:31,594 basehttp "GET /api/account/register/ HTTP/1.1" 500 86428
ERROR 2025-03-14 00:15:31,812 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\renderers.py", line 726, in render
    template = loader.get_template(self.template)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2025-03-14 00:15:31,812 basehttp "GET /api/account/register/ HTTP/1.1" 500 86428
ERROR 2025-03-14 00:15:35,456 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\renderers.py", line 726, in render
    template = loader.get_template(self.template)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2025-03-14 00:15:35,457 basehttp "GET /api/account/register/ HTTP/1.1" 500 86291
INFO 2025-03-14 00:16:51,817 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:16:51,908 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:16:52,548 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:16:52,654 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:17:29,533 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:17:29,622 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:17:29,822 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:17:29,918 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:17:41,224 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:17:41,348 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:17:41,531 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:17:41,671 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:18:04,187 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:18:04,476 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:18:11,412 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:18:41,205 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:18:43,402 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:19:51,012 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 00:19:51,425 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 00:19:56,804 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:19:56,805 basehttp "GET /api/account/register/ HTTP/1.1" 400 5224
INFO 2025-03-14 00:19:57,446 basehttp "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2025-03-14 00:19:57,448 basehttp "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
INFO 2025-03-14 00:19:57,449 basehttp "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
INFO 2025-03-14 00:19:57,450 basehttp "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2025-03-14 00:19:57,452 basehttp "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2025-03-14 00:19:57,454 basehttp "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2025-03-14 00:19:57,454 basehttp "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
INFO 2025-03-14 00:19:57,459 basehttp "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
INFO 2025-03-14 00:19:57,466 basehttp "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2025-03-14 00:19:57,466 basehttp "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
INFO 2025-03-14 00:19:57,470 basehttp "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2025-03-14 00:19:57,479 basehttp "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
WARNING 2025-03-14 00:20:03,651 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:20:03,651 basehttp "GET /api/account/register/ HTTP/1.1" 400 5224
INFO 2025-03-14 00:20:06,940 basehttp "OPTIONS /api/account/register/ HTTP/1.1" 200 5576
WARNING 2025-03-14 00:20:17,986 log Method Not Allowed: /api/account/register/
WARNING 2025-03-14 00:20:17,986 basehttp "POST /api/account/register/ HTTP/1.1" 405 41
INFO 2025-03-14 00:20:17,987 basehttp code 400, message Bad request syntax ('{')
WARNING 2025-03-14 00:20:17,987 basehttp "{" 400 -
INFO 2025-03-14 00:21:26,970 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:21:27,758 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 00:21:31,876 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:21:31,876 basehttp "POST /api/account/register/ HTTP/1.1" 400 76
INFO 2025-03-14 00:21:31,876 basehttp code 400, message Bad request syntax ('{')
WARNING 2025-03-14 00:21:31,876 basehttp "{" 400 -
WARNING 2025-03-14 00:21:56,103 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:21:56,103 basehttp "POST /api/account/register/ HTTP/1.1" 400 76
INFO 2025-03-14 00:21:56,103 basehttp code 400, message Bad request syntax ('----------------------------903331166822094382568150')
WARNING 2025-03-14 00:21:56,105 basehttp "----------------------------903331166822094382568150" 400 -
WARNING 2025-03-14 00:22:12,262 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:22:12,263 basehttp "POST /api/account/register/ HTTP/1.1" 400 76
INFO 2025-03-14 00:22:12,263 basehttp code 400, message Bad request syntax ('{')
WARNING 2025-03-14 00:22:12,263 basehttp "{" 400 -
WARNING 2025-03-14 00:22:48,525 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:22:48,525 basehttp "POST /api/account/register/ HTTP/1.1" 400 76
INFO 2025-03-14 00:22:48,525 basehttp code 400, message Bad request syntax ('{')
WARNING 2025-03-14 00:22:48,525 basehttp "{" 400 -
WARNING 2025-03-14 00:23:57,671 log Bad Request: /api/account/register/
WARNING 2025-03-14 00:23:57,671 basehttp "POST /api/account/register/ HTTP/1.1" 400 76
INFO 2025-03-14 00:23:57,671 basehttp code 400, message Bad request syntax ('{')
WARNING 2025-03-14 00:23:57,671 basehttp "{" 400 -
ERROR 2025-03-14 00:24:39,633 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 12, in post
    serializer.save()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "D:\code\Soulwhisper\backend\apps\account\serializers.py", line 13, in create
    user = CustomUser.objects.create_user(
  File "D:\code\Soulwhisper\backend\apps\account\models.py", line 10, in create_user
    email = self.normalize_email(email)
AttributeError: 'CustomUserManager' object has no attribute 'normalize_email'
ERROR 2025-03-14 00:24:39,635 basehttp "POST /api/account/register/ HTTP/1.1" 500 107831
ERROR 2025-03-14 00:24:44,472 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 12, in post
    serializer.save()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "D:\code\Soulwhisper\backend\apps\account\serializers.py", line 13, in create
    user = CustomUser.objects.create_user(
  File "D:\code\Soulwhisper\backend\apps\account\models.py", line 10, in create_user
    email = self.normalize_email(email)
AttributeError: 'CustomUserManager' object has no attribute 'normalize_email'
ERROR 2025-03-14 00:24:44,474 basehttp "POST /api/account/register/ HTTP/1.1" 500 107831
INFO 2025-03-14 00:26:08,760 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:26:09,539 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:26:12,778 basehttp "POST /api/account/logout/ HTTP/1.1" 200 32
INFO 2025-03-14 00:28:44,193 basehttp "POST /api/account/logout/ HTTP/1.1" 200 32
INFO 2025-03-14 00:28:44,552 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:28:45,287 autoreload Watching for file changes with StatReloader
ERROR 2025-03-14 00:28:56,382 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 14, in post
    serializer.save()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "D:\code\Soulwhisper\backend\apps\account\serializers.py", line 13, in create
    user = CustomUser.objects.create_user(
  File "D:\code\Soulwhisper\backend\apps\account\models.py", line 10, in create_user
    email = self.normalize_email(email)
AttributeError: 'CustomUserManager' object has no attribute 'normalize_email'
ERROR 2025-03-14 00:28:56,384 basehttp "POST /api/account/register/ HTTP/1.1" 500 107683
ERROR 2025-03-14 00:29:23,012 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 14, in post
    serializer.save()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "D:\code\Soulwhisper\backend\apps\account\serializers.py", line 13, in create
    user = CustomUser.objects.create_user(
  File "D:\code\Soulwhisper\backend\apps\account\models.py", line 10, in create_user
    email = self.normalize_email(email)
AttributeError: 'CustomUserManager' object has no attribute 'normalize_email'
ERROR 2025-03-14 00:29:23,013 basehttp "POST /api/account/register/ HTTP/1.1" 500 107683
INFO 2025-03-14 00:41:02,981 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 00:41:03,943 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:44:46,084 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 00:44:46,441 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:51:09,303 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 00:51:09,653 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:52:13,403 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 00:52:13,748 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 00:57:38,594 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 00:57:38,986 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 08:15:39,257 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 08:16:56,103 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 08:16:56,965 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 08:39:51,793 log Not Found: /api/account/register/
WARNING 2025-03-14 08:39:51,793 basehttp "POST /api/account/register/ HTTP/1.1" 404 2474
INFO 2025-03-14 08:43:03,192 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 08:43:04,227 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 08:50:54,441 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 08:50:55,291 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 08:52:14,980 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-14 08:52:15,721 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 08:53:06,788 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 08:53:07,589 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 08:54:05,225 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 08:58:51,250 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 08:58:51,985 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 09:00:09,057 log Bad Request: /api/account/register/
WARNING 2025-03-14 09:00:09,057 basehttp "POST /api/account/register/ HTTP/1.1" 400 108
ERROR 2025-03-14 09:00:22,274 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: account_customuser.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 22, in post
    user.save()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: account_customuser.email
ERROR 2025-03-14 09:00:22,278 basehttp "POST /api/account/register/ HTTP/1.1" 500 176530
INFO 2025-03-14 09:01:47,528 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
INFO 2025-03-14 09:03:49,756 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
WARNING 2025-03-14 09:04:31,900 log Unauthorized: /api/account/login/
WARNING 2025-03-14 09:04:31,900 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
WARNING 2025-03-14 09:04:48,051 log Unauthorized: /api/account/login/
WARNING 2025-03-14 09:04:48,052 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
INFO 2025-03-14 09:06:04,124 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
INFO 2025-03-14 09:06:15,790 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
INFO 2025-03-14 09:07:00,293 basehttp "POST /api/account/logout/ HTTP/1.1" 200 32
WARNING 2025-03-14 09:09:16,080 log Bad Request: /api/account/register/
WARNING 2025-03-14 09:09:16,081 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
WARNING 2025-03-14 09:09:22,077 log Bad Request: /api/account/register/
WARNING 2025-03-14 09:09:22,078 basehttp "POST /api/account/register/ HTTP/1.1" 400 33
INFO 2025-03-14 09:09:30,839 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
WARNING 2025-03-14 09:13:47,252 log Unauthorized: /api/account/login/
WARNING 2025-03-14 09:13:47,252 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
INFO 2025-03-14 09:16:41,907 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 09:16:42,688 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:17:54,716 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 09:17:55,466 autoreload Watching for file changes with StatReloader
ERROR 2025-03-14 09:18:00,749 log Internal Server Error: /api/account/login/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 53, in post
    login(request, user)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2025-03-14 09:18:00,751 basehttp "POST /api/account/login/ HTTP/1.1" 500 118720
INFO 2025-03-14 09:45:40,868 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:45:41,688 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:46:18,466 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 09:46:19,234 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:46:38,532 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-14 09:46:39,297 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:46:46,645 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:46:47,434 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:47:13,438 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:47:14,165 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:47:25,778 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:47:26,583 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:47:36,053 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:47:36,812 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:47:44,085 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:47:44,847 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:48:06,238 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:48:06,968 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:48:49,359 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:48:50,139 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:48:54,142 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:48:54,901 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:49:08,699 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:49:09,443 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:49:29,556 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:52:13,933 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:52:14,667 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:52:14,938 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:52:15,715 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:52:26,386 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:52:27,156 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:52:27,316 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 09:52:28,117 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 09:56:38,577 log Bad Request: /api/account/register/
WARNING 2025-03-14 09:56:38,578 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
ERROR 2025-03-14 09:56:53,165 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table account_customuser has no column named avatar

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 29, in post
    user.save()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table account_customuser has no column named avatar
ERROR 2025-03-14 09:56:53,169 basehttp "POST /api/account/register/ HTTP/1.1" 500 183115
WARNING 2025-03-14 09:57:23,538 log Not Found: /account/register/
WARNING 2025-03-14 09:57:23,538 basehttp "POST /account/register/ HTTP/1.1" 404 2574
ERROR 2025-03-14 09:57:32,833 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table account_customuser has no column named avatar

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 29, in post
    user.save()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table account_customuser has no column named avatar
ERROR 2025-03-14 09:57:32,836 basehttp "POST /api/account/register/ HTTP/1.1" 500 183115
INFO 2025-03-14 09:58:47,330 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 09:58:57,752 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
INFO 2025-03-14 09:59:49,173 basehttp "POST /api/account/login/ HTTP/1.1" 200 153
INFO 2025-03-14 10:00:31,161 basehttp "POST /api/account/login/ HTTP/1.1" 200 153
INFO 2025-03-14 10:01:36,816 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
WARNING 2025-03-14 10:03:05,372 log Not Found: /api/account/rest-password/
WARNING 2025-03-14 10:03:05,372 basehttp "POST /api/account/rest-password/ HTTP/1.1" 404 3988
WARNING 2025-03-14 10:03:51,387 log Forbidden: /api/account/change-password/
WARNING 2025-03-14 10:03:51,387 basehttp "POST /api/account/change-password/ HTTP/1.1" 403 58
WARNING 2025-03-14 10:04:12,686 log Forbidden: /api/account/change-password/
WARNING 2025-03-14 10:04:12,687 basehttp "POST /api/account/change-password/ HTTP/1.1" 403 58
WARNING 2025-03-14 10:05:23,137 log Forbidden: /api/account/change-password/
WARNING 2025-03-14 10:05:23,138 basehttp "POST /api/account/change-password/ HTTP/1.1" 403 58
WARNING 2025-03-14 10:05:56,437 log Forbidden: /api/account/change-password/
WARNING 2025-03-14 10:05:56,437 basehttp "POST /api/account/change-password/ HTTP/1.1" 403 58
WARNING 2025-03-14 10:42:13,912 log Forbidden: /api/account/change-password/
WARNING 2025-03-14 10:42:13,912 basehttp "POST /api/account/change-password/ HTTP/1.1" 403 58
WARNING 2025-03-14 10:43:50,282 log Not Found: /
WARNING 2025-03-14 10:43:50,283 basehttp "GET / HTTP/1.1" 404 2504
WARNING 2025-03-14 10:43:50,326 log Not Found: /favicon.ico
WARNING 2025-03-14 10:43:50,326 basehttp "GET /favicon.ico HTTP/1.1" 404 2555
WARNING 2025-03-14 10:45:36,169 log Method Not Allowed: /api/account/change-password/
WARNING 2025-03-14 10:45:36,170 basehttp "GET /api/account/change-password/ HTTP/1.1" 405 5695
INFO 2025-03-14 10:45:36,185 basehttp "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,186 basehttp "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,186 basehttp "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,188 basehttp "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,190 basehttp "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,191 basehttp "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,191 basehttp "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,192 basehttp "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,194 basehttp "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,194 basehttp "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,195 basehttp "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,196 basehttp "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
INFO 2025-03-14 10:45:36,462 basehttp "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 200 540434
INFO 2025-03-14 10:46:06,039 basehttp "POST /api/account/change-password/ HTTP/1.1" 200 5674
WARNING 2025-03-14 10:47:43,363 log Method Not Allowed: /api/account/change-password/
WARNING 2025-03-14 10:47:43,364 basehttp "GET /api/account/change-password/ HTTP/1.1" 405 5695
WARNING 2025-03-14 10:50:45,951 log Method Not Allowed: /api/account/register/
WARNING 2025-03-14 10:50:45,952 basehttp "GET /api/account/register/ HTTP/1.1" 405 5632
WARNING 2025-03-14 10:51:04,129 log Bad Request: /api/account/register/
WARNING 2025-03-14 10:51:04,130 basehttp "POST /api/account/register/ HTTP/1.1" 400 5612
WARNING 2025-03-14 10:51:37,363 log Forbidden: /api/account/change-password/
WARNING 2025-03-14 10:51:37,364 basehttp "POST /api/account/change-password/ HTTP/1.1" 403 58
WARNING 2025-03-14 10:57:21,002 log Forbidden: /api/account/change-password/
WARNING 2025-03-14 10:57:21,002 basehttp "POST /api/account/change-password/ HTTP/1.1" 403 58
INFO 2025-03-14 11:02:29,192 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:02:29,951 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:02:30,158 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:02:30,926 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:03:00,968 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:04:18,471 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:04:18,703 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:04:19,094 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:04:19,409 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:04:19,629 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:04:20,079 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:05:58,965 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:05:59,375 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:05:59,800 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:05:59,889 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:06:00,333 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:06:00,833 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:06:35,676 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:06:36,129 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:06:36,454 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:06:36,588 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:06:37,101 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:06:37,496 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:07:28,562 log Unauthorized: /api/account/register/
WARNING 2025-03-14 11:07:28,562 basehttp "POST /api/account/register/ HTTP/1.1" 401 58
WARNING 2025-03-14 11:07:52,505 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:07:52,506 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
WARNING 2025-03-14 11:07:54,717 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:07:54,718 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
INFO 2025-03-14 11:08:33,780 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:08:33,865 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:08:34,111 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:08:34,578 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:08:34,687 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:08:34,947 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:08:59,344 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:09:22,540 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:09:22,541 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
WARNING 2025-03-14 11:09:24,130 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:09:24,130 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
INFO 2025-03-14 11:09:51,212 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:09:51,309 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:09:52,023 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:09:52,118 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:10:01,321 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:10:01,321 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
WARNING 2025-03-14 11:10:05,203 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:10:05,203 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
INFO 2025-03-14 11:16:13,611 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:16:24,408 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:16:24,408 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
INFO 2025-03-14 11:17:41,822 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:17:47,268 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:17:47,268 basehttp "POST /api/account/login/ HTTP/1.1" 401 58
INFO 2025-03-14 11:19:21,243 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:19:22,162 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:19:25,984 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:19:26,842 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:19:33,835 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:19:34,720 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:19:56,010 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:19:56,888 autoreload Watching for file changes with StatReloader
ERROR 2025-03-14 11:20:23,003 log Internal Server Error: /api/account/register/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: account_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 20, in post
    if CustomUser.objects.filter(username=data.get('username')).exists():
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\query.py", line 598, in has_results
    return compiler.has_results()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: account_customuser
ERROR 2025-03-14 11:20:23,007 basehttp "POST /api/account/register/ HTTP/1.1" 500 155851
INFO 2025-03-14 11:22:22,208 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:22:31,292 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
ERROR 2025-03-14 11:23:05,837 log Internal Server Error: /api/account/login/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 51, in post
    token, created = Token.objects.get_or_create(user=user)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\query.py", line 1465, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\query.py", line 1276, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\query.py", line 1253, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "testuser": Must be "User" instance.
ERROR 2025-03-14 11:23:05,840 basehttp "POST /api/account/login/ HTTP/1.1" 500 149217
INFO 2025-03-14 11:24:05,513 autoreload D:\code\Soulwhisper\backend\apps\account\models.py changed, reloading.
INFO 2025-03-14 11:24:06,367 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:24:34,220 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:24:35,037 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:24:58,609 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:24:59,442 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:25:04,316 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:25:05,174 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:25:08,997 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:25:09,837 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:26:08,037 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:27:34,885 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
INFO 2025-03-14 11:27:42,395 basehttp "POST /api/account/login/ HTTP/1.1" 200 204
WARNING 2025-03-14 11:28:27,221 log Forbidden: /api/account/update/
WARNING 2025-03-14 11:28:27,222 basehttp "POST /api/account/update/ HTTP/1.1" 403 45
INFO 2025-03-14 11:32:13,380 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:32:14,117 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:32:28,819 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:32:29,546 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:32:32,249 log Forbidden: /api/account/update/
WARNING 2025-03-14 11:32:32,249 basehttp "POST /api/account/update/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:32:36,256 log Forbidden: /api/account/update/
WARNING 2025-03-14 11:32:36,257 basehttp "POST /api/account/update/ HTTP/1.1" 403 45
INFO 2025-03-14 11:34:35,944 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:34:36,655 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:34:40,438 log Forbidden: /api/account/update/
WARNING 2025-03-14 11:34:40,439 basehttp "POST /api/account/update/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:34:42,513 log Forbidden: /api/account/update/
WARNING 2025-03-14 11:34:42,513 basehttp "POST /api/account/update/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:34:44,412 log Forbidden: /api/account/update/
WARNING 2025-03-14 11:34:44,412 basehttp "POST /api/account/update/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:34:56,343 log Forbidden: /api/account/login/
WARNING 2025-03-14 11:34:56,343 basehttp "POST /api/account/login/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:35:02,766 log Forbidden: /api/account/register/
WARNING 2025-03-14 11:35:02,766 basehttp "POST /api/account/register/ HTTP/1.1" 403 45
INFO 2025-03-14 11:35:43,278 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:35:44,029 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:35:48,676 log Forbidden: /api/account/register/
WARNING 2025-03-14 11:35:48,676 basehttp "POST /api/account/register/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:35:51,265 log Forbidden: /api/account/register/
WARNING 2025-03-14 11:35:51,265 basehttp "POST /api/account/register/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:36:49,511 log Forbidden: /api/account/register/
WARNING 2025-03-14 11:36:49,512 basehttp "POST /api/account/register/ HTTP/1.1" 403 45
INFO 2025-03-14 11:37:08,816 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:37:14,474 log Forbidden: /api/account/register/
WARNING 2025-03-14 11:37:14,475 basehttp "POST /api/account/register/ HTTP/1.1" 403 45
WARNING 2025-03-14 11:37:17,365 log Forbidden: /api/account/register/
WARNING 2025-03-14 11:37:17,366 basehttp "POST /api/account/register/ HTTP/1.1" 403 45
INFO 2025-03-14 11:41:20,914 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 11:41:21,651 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:41:33,817 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:41:46,504 log Bad Request: /api/account/register/
WARNING 2025-03-14 11:41:46,504 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
INFO 2025-03-14 11:41:50,542 basehttp "POST /api/account/login/ HTTP/1.1" 200 204
INFO 2025-03-14 11:41:56,370 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
WARNING 2025-03-14 11:45:43,335 log Not Found: /api/account/resetpassword/
WARNING 2025-03-14 11:45:43,336 basehttp "POST /api/account/resetpassword/ HTTP/1.1" 404 3988
WARNING 2025-03-14 11:46:06,080 log Not Found: /api/account/resetpassword/
WARNING 2025-03-14 11:46:06,080 basehttp "POST /api/account/resetpassword/ HTTP/1.1" 404 3988
WARNING 2025-03-14 11:47:10,520 log Not Found: /api/account/resetpassword/
WARNING 2025-03-14 11:47:10,521 basehttp "POST /api/account/resetpassword/ HTTP/1.1" 404 3988
WARNING 2025-03-14 11:47:48,653 log Not Found: /api/account/reset-password/
WARNING 2025-03-14 11:47:48,653 basehttp "POST /api/account/reset-password/ HTTP/1.1" 404 48
WARNING 2025-03-14 11:47:53,901 log Bad Request: /api/account/register/
WARNING 2025-03-14 11:47:53,902 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
INFO 2025-03-14 11:48:00,292 basehttp "POST /api/account/login/ HTTP/1.1" 200 207
INFO 2025-03-14 11:48:13,977 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
WARNING 2025-03-14 11:48:27,235 log Not Found: /api/account/reset-password/
WARNING 2025-03-14 11:48:27,235 basehttp "POST /api/account/reset-password/ HTTP/1.1" 404 48
WARNING 2025-03-14 11:49:14,443 log Not Found: /api/account/change-password/
WARNING 2025-03-14 11:49:14,443 basehttp "POST /api/account/change-password/ HTTP/1.1" 404 27
WARNING 2025-03-14 11:49:26,199 log Not Found: /api/account/change-password/
WARNING 2025-03-14 11:49:26,200 basehttp "POST /api/account/change-password/ HTTP/1.1" 404 27
ERROR 2025-03-14 11:50:06,304 log Internal Server Error: /api/account/delete/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: diary_diary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 192, in post
    user.delete()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1131, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\deletion.py", line 348, in collect
    if getattr(on_delete, "lazy_sub_objs", False) or sub_objs:
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 412, in __bool__
    self._fetch_all()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: diary_diary
ERROR 2025-03-14 11:50:06,307 basehttp "POST /api/account/delete/ HTTP/1.1" 500 168940
ERROR 2025-03-14 11:50:16,878 log Internal Server Error: /api/account/delete/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: diary_diary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 192, in post
    user.delete()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1131, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\deletion.py", line 348, in collect
    if getattr(on_delete, "lazy_sub_objs", False) or sub_objs:
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 412, in __bool__
    self._fetch_all()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: diary_diary
ERROR 2025-03-14 11:50:16,880 basehttp "POST /api/account/delete/ HTTP/1.1" 500 169115
INFO 2025-03-14 11:51:26,834 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-14 11:51:27,549 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:51:34,407 log Not Found: /api/account/change-password/
WARNING 2025-03-14 11:51:34,408 basehttp "POST /api/account/change-password/ HTTP/1.1" 404 27
INFO 2025-03-14 11:51:58,286 basehttp "POST /api/account/change-password/ HTTP/1.1" 200 44
WARNING 2025-03-14 11:52:12,631 log Not Found: /api/account/reset-password/
WARNING 2025-03-14 11:52:12,632 basehttp "POST /api/account/reset-password/ HTTP/1.1" 404 48
INFO 2025-03-14 11:53:29,706 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-14 11:53:30,450 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:53:46,464 log Not Found: /api/account/reset-password/
WARNING 2025-03-14 11:53:46,465 basehttp "POST /api/account/reset-password/ HTTP/1.1" 404 48
WARNING 2025-03-14 11:53:48,153 log Not Found: /api/account/reset-password/
WARNING 2025-03-14 11:53:48,153 basehttp "POST /api/account/reset-password/ HTTP/1.1" 404 48
WARNING 2025-03-14 11:53:50,133 log Not Found: /api/account/reset-password/
WARNING 2025-03-14 11:53:50,134 basehttp "POST /api/account/reset-password/ HTTP/1.1" 404 48
INFO 2025-03-14 11:54:00,521 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:54:04,425 log Bad Request: /api/account/register/
WARNING 2025-03-14 11:54:04,425 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
WARNING 2025-03-14 11:54:12,278 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:54:12,279 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
WARNING 2025-03-14 11:54:30,404 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:54:30,405 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
INFO 2025-03-14 11:54:40,716 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
WARNING 2025-03-14 11:54:48,510 log Unauthorized: /api/account/change-password/
WARNING 2025-03-14 11:54:48,510 basehttp "POST /api/account/change-password/ HTTP/1.1" 401 58
WARNING 2025-03-14 11:54:54,624 log Unauthorized: /api/account/change-password/
WARNING 2025-03-14 11:54:54,625 basehttp "POST /api/account/change-password/ HTTP/1.1" 401 58
WARNING 2025-03-14 11:54:57,577 log Unauthorized: /api/account/change-password/
WARNING 2025-03-14 11:54:57,578 basehttp "POST /api/account/change-password/ HTTP/1.1" 401 58
WARNING 2025-03-14 11:55:18,176 log Bad Request: /api/account/register/
WARNING 2025-03-14 11:55:18,176 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
WARNING 2025-03-14 11:55:24,920 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:55:24,921 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
WARNING 2025-03-14 11:55:45,792 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:55:45,792 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
INFO 2025-03-14 11:56:42,267 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-14 11:56:43,030 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:56:47,912 autoreload D:\code\Soulwhisper\backend\apps\account\urls.py changed, reloading.
INFO 2025-03-14 11:56:48,647 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:56:55,705 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 11:56:56,443 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 11:57:30,922 log Bad Request: /api/account/register/
WARNING 2025-03-14 11:57:30,922 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
WARNING 2025-03-14 11:57:34,087 log Unauthorized: /api/account/login/
WARNING 2025-03-14 11:57:34,088 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
INFO 2025-03-14 11:58:19,792 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 11:58:31,446 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
INFO 2025-03-14 11:58:47,528 basehttp "POST /api/account/login/ HTTP/1.1" 200 204
INFO 2025-03-14 11:59:15,233 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
INFO 2025-03-14 11:59:47,553 basehttp "POST /api/account/change-password/ HTTP/1.1" 200 44
INFO 2025-03-14 12:02:13,802 basehttp "GET /api/account/info/?username=testuser HTTP/1.1" 200 261
INFO 2025-03-14 12:02:23,940 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
INFO 2025-03-14 12:02:28,032 basehttp "GET /api/account/info/?username=testuser HTTP/1.1" 200 261
INFO 2025-03-14 12:02:34,272 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
INFO 2025-03-14 12:03:51,340 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 12:03:52,112 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 12:03:55,887 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 12:03:56,615 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 12:04:04,669 log Unauthorized: /api/account/update/
WARNING 2025-03-14 12:04:04,669 basehttp "POST /api/account/update/ HTTP/1.1" 401 58
WARNING 2025-03-14 12:04:51,919 log Unauthorized: /api/account/update/
WARNING 2025-03-14 12:04:51,919 basehttp "POST /api/account/update/ HTTP/1.1" 401 58
INFO 2025-03-14 12:05:07,421 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 12:05:08,172 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 12:05:12,012 basehttp "POST /api/account/update/ HTTP/1.1" 200 52
INFO 2025-03-14 12:05:19,453 basehttp "GET /api/account/info/?username=testuser HTTP/1.1" 200 324
WARNING 2025-03-14 12:11:05,876 log Not Found: /api/account/loginout
WARNING 2025-03-14 12:11:05,876 basehttp "POST /api/account/loginout HTTP/1.1" 404 3773
WARNING 2025-03-14 12:11:15,214 log Not Found: /api/account/loginout/
WARNING 2025-03-14 12:11:15,214 basehttp "POST /api/account/loginout/ HTTP/1.1" 404 3776
INFO 2025-03-14 12:11:35,653 basehttp "POST /api/account/logout/ HTTP/1.1" 200 32
ERROR 2025-03-14 12:11:46,541 log Internal Server Error: /api/account/delete/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: diary_diary

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 179, in post
    user.delete()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1131, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\deletion.py", line 348, in collect
    if getattr(on_delete, "lazy_sub_objs", False) or sub_objs:
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 412, in __bool__
    self._fetch_all()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: diary_diary
ERROR 2025-03-14 12:11:46,543 basehttp "POST /api/account/delete/ HTTP/1.1" 500 169236
INFO 2025-03-14 12:12:34,667 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 12:12:35,407 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 12:12:50,092 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 12:12:50,827 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 12:13:18,300 autoreload Watching for file changes with StatReloader
ERROR 2025-03-14 12:13:25,669 log Internal Server Error: /api/account/delete/
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: chat_chatsession

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\code\Soulwhisper\backend\apps\account\views.py", line 179, in post
    user.delete()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\base.py", line 1131, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\deletion.py", line 348, in collect
    if getattr(on_delete, "lazy_sub_objs", False) or sub_objs:
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 412, in __bool__
    self._fetch_all()
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: chat_chatsession
ERROR 2025-03-14 12:13:25,673 basehttp "POST /api/account/delete/ HTTP/1.1" 500 169634
INFO 2025-03-14 12:15:13,652 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 12:15:19,867 basehttp "POST /api/account/delete/ HTTP/1.1" 200 40
WARNING 2025-03-14 12:15:28,918 log Unauthorized: /api/account/login/
WARNING 2025-03-14 12:15:28,918 basehttp "POST /api/account/login/ HTTP/1.1" 401 32
INFO 2025-03-14 12:15:36,359 basehttp "POST /api/account/register/ HTTP/1.1" 201 43
WARNING 2025-03-14 12:15:40,230 log Unauthorized: /api/account/change-password/
WARNING 2025-03-14 12:15:40,231 basehttp "POST /api/account/change-password/ HTTP/1.1" 401 58
WARNING 2025-03-14 12:18:57,889 log Method Not Allowed: /api/diary/asr_view/
WARNING 2025-03-14 12:18:57,890 basehttp "GET /api/diary/asr_view/ HTTP/1.1" 405 47
WARNING 2025-03-14 12:19:02,312 log Bad Request: /api/diary/asr_view/
WARNING 2025-03-14 12:19:02,313 basehttp "POST /api/diary/asr_view/ HTTP/1.1" 400 61
INFO 2025-03-14 12:36:25,654 autoreload D:\code\Soulwhisper\backend\apps\account\views.py changed, reloading.
INFO 2025-03-14 12:36:26,401 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:30:56,326 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 15:32:31,899 log Not Found: /api/diary/list
WARNING 2025-03-14 15:32:31,899 basehttp "GET /api/diary/list HTTP/1.1" 404 2828
INFO 2025-03-14 15:33:55,663 autoreload D:\code\Soulwhisper\backend\apps\diary\urls.py changed, reloading.
INFO 2025-03-14 15:33:56,393 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:34:29,673 autoreload D:\code\Soulwhisper\backend\apps\diary\urls.py changed, reloading.
INFO 2025-03-14 15:34:30,427 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:34:44,037 autoreload D:\code\Soulwhisper\backend\apps\diary\urls.py changed, reloading.
INFO 2025-03-14 15:34:44,777 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:35:11,444 autoreload D:\code\Soulwhisper\backend\apps\diary\urls.py changed, reloading.
INFO 2025-03-14 15:35:12,220 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:36:12,833 autoreload D:\code\Soulwhisper\backend\apps\diary\urls.py changed, reloading.
INFO 2025-03-14 15:36:13,645 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:37:16,804 autoreload D:\code\Soulwhisper\backend\apps\diary\urls.py changed, reloading.
INFO 2025-03-14 15:37:17,550 autoreload Watching for file changes with StatReloader
ERROR 2025-03-14 15:39:41,545 log Internal Server Error: /api/diary/create
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/diary/create/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2025-03-14 15:39:41,546 basehttp "POST /api/diary/create HTTP/1.1" 500 76389
WARNING 2025-03-14 15:40:03,170 log Unauthorized: /api/diary/create/
WARNING 2025-03-14 15:40:03,170 basehttp "POST /api/diary/create/ HTTP/1.1" 401 58
WARNING 2025-03-14 15:40:39,990 log Bad Request: /api/account/register/
WARNING 2025-03-14 15:40:39,991 basehttp "POST /api/account/register/ HTTP/1.1" 400 36
INFO 2025-03-14 15:40:59,487 basehttp "POST /api/account/login/ HTTP/1.1" 200 204
INFO 2025-03-14 15:41:22,397 basehttp "POST /api/diary/create/ HTTP/1.1" 201 45
INFO 2025-03-14 15:44:00,241 basehttp "GET /api/diary/1 HTTP/1.1" 301 0
WARNING 2025-03-14 15:44:00,264 log Bad Request: /api/diary/1/
WARNING 2025-03-14 15:44:00,265 basehttp "GET /api/diary/1/ HTTP/1.1" 400 128
WARNING 2025-03-14 15:44:26,988 log Not Found: /api/diary/
WARNING 2025-03-14 15:44:26,988 basehttp "GET /api/diary/?diary_id=1 HTTP/1.1" 404 4428
WARNING 2025-03-14 15:44:56,685 log Bad Request: /api/diary/1/
WARNING 2025-03-14 15:44:56,685 basehttp "GET /api/diary/1/ HTTP/1.1" 400 128
WARNING 2025-03-14 15:48:10,352 log Method Not Allowed: /api/diary/create/
WARNING 2025-03-14 15:48:10,352 basehttp "GET /api/diary/create/ HTTP/1.1" 405 40
INFO 2025-03-14 15:48:14,691 basehttp "POST /api/diary/create/ HTTP/1.1" 201 45
ERROR 2025-03-14 15:49:11,069 log Internal Server Error: /api/diary/update/1
Traceback (most recent call last):
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "D:\code\Soulwhisper\backend\venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/diary/update/1/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2025-03-14 15:49:11,070 basehttp "POST /api/diary/update/1 HTTP/1.1" 500 76565
INFO 2025-03-14 15:49:48,937 basehttp "GET /api/diary/1 HTTP/1.1" 301 0
WARNING 2025-03-14 15:49:48,959 log Bad Request: /api/diary/1/
WARNING 2025-03-14 15:49:48,959 basehttp "GET /api/diary/1/ HTTP/1.1" 400 128
WARNING 2025-03-14 15:50:07,061 log Bad Request: /api/diary/1/
WARNING 2025-03-14 15:50:07,062 basehttp "GET /api/diary/1/ HTTP/1.1" 400 128
WARNING 2025-03-14 15:50:17,391 log Method Not Allowed: /api/diary/update/1/
WARNING 2025-03-14 15:50:17,392 basehttp "POST /api/diary/update/1/ HTTP/1.1" 405 41
WARNING 2025-03-14 15:50:36,414 log Method Not Allowed: /api/diary/update/1/
WARNING 2025-03-14 15:50:36,415 basehttp "POST /api/diary/update/1/ HTTP/1.1" 405 41
INFO 2025-03-14 15:50:45,769 basehttp "PUT /api/diary/update/1/ HTTP/1.1" 200 32
INFO 2025-03-14 15:51:25,198 basehttp "GET /api/diary/list/ HTTP/1.1" 200 581
INFO 2025-03-14 15:53:00,299 basehttp "POST /api/diary/1/comment/ HTTP/1.1" 201 47
INFO 2025-03-14 15:53:25,117 basehttp "POST /api/diary/1/comment/ HTTP/1.1" 201 47
INFO 2025-03-14 15:54:35,121 basehttp "DELETE /api/diary/comment/1/delete/ HTTP/1.1" 200 32
WARNING 2025-03-14 15:55:01,058 log Bad Request: /api/diary/1/
WARNING 2025-03-14 15:55:01,059 basehttp "GET /api/diary/1/ HTTP/1.1" 400 128
WARNING 2025-03-14 15:55:24,721 log Method Not Allowed: /api/diary/1/
WARNING 2025-03-14 15:55:24,721 basehttp "DELETE /api/diary/1/ HTTP/1.1" 405 43
WARNING 2025-03-14 15:55:33,424 log Method Not Allowed: /api/diary/1/
WARNING 2025-03-14 15:55:33,424 basehttp "DELETE /api/diary/1/ HTTP/1.1" 405 43
INFO 2025-03-14 15:55:44,809 basehttp "DELETE /api/diary/delete/1/ HTTP/1.1" 200 32
WARNING 2025-03-14 15:57:00,600 log Method Not Allowed: /api/diary/update/1/
WARNING 2025-03-14 15:57:00,600 basehttp "POST /api/diary/update/1/ HTTP/1.1" 405 41
INFO 2025-03-14 15:57:59,001 basehttp "POST /api/diary/2/like/ HTTP/1.1" 200 41
WARNING 2025-03-14 15:58:14,227 log Bad Request: /api/diary/1/
WARNING 2025-03-14 15:58:14,227 basehttp "GET /api/diary/1/ HTTP/1.1" 400 45
WARNING 2025-03-14 15:58:20,554 log Bad Request: /api/diary/2/
WARNING 2025-03-14 15:58:20,555 basehttp "GET /api/diary/2/ HTTP/1.1" 400 128
INFO 2025-03-14 16:00:04,728 autoreload D:\code\Soulwhisper\backend\apps\diary\models.py changed, reloading.
INFO 2025-03-14 16:00:05,461 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 16:00:24,494 autoreload D:\code\Soulwhisper\backend\apps\diary\views.py changed, reloading.
INFO 2025-03-14 16:00:25,258 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 16:00:29,084 autoreload D:\code\Soulwhisper\backend\apps\diary\views.py changed, reloading.
INFO 2025-03-14 16:00:29,836 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 16:01:09,766 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 16:01:17,493 basehttp "GET /api/diary/2/ HTTP/1.1" 200 436
INFO 2025-03-14 16:01:23,892 basehttp "GET /api/diary/2/ HTTP/1.1" 200 436
INFO 2025-03-14 16:01:44,225 basehttp "POST /api/diary/2/like/ HTTP/1.1" 200 41
INFO 2025-03-14 16:02:50,099 basehttp "GET /api/diary/list/ HTTP/1.1" 200 300
WARNING 2025-03-14 16:05:32,674 log Bad Request: /api/diary/comment/2/delete/
WARNING 2025-03-14 16:05:32,675 basehttp "DELETE /api/diary/comment/2/delete/ HTTP/1.1" 400 52
INFO 2025-03-14 16:05:47,981 basehttp "POST /api/diary/2/comment/ HTTP/1.1" 201 47
WARNING 2025-03-14 16:06:05,954 log Bad Request: /api/diary/comment/2/delete/
WARNING 2025-03-14 16:06:05,954 basehttp "DELETE /api/diary/comment/2/delete/ HTTP/1.1" 400 52
INFO 2025-03-14 16:09:11,313 autoreload D:\code\Soulwhisper\backend\config\settings.py changed, reloading.
INFO 2025-03-14 16:09:12,045 autoreload Watching for file changes with StatReloader
WARNING 2025-03-14 16:13:24,199 log Not Found: /api/docs/
WARNING 2025-03-14 16:13:24,199 basehttp "GET /api/docs/ HTTP/1.1" 404 2549
WARNING 2025-03-14 16:13:24,345 log Not Found: /favicon.ico
WARNING 2025-03-14 16:13:24,345 basehttp "GET /favicon.ico HTTP/1.1" 404 2555
INFO 2025-03-14 16:13:54,553 autoreload D:\code\Soulwhisper\backend\config\urls.py changed, reloading.
INFO 2025-03-14 16:13:55,347 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 16:15:57,776 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 16:16:03,959 basehttp "GET /api/docs/ HTTP/1.1" 200 68371
INFO 2025-03-14 16:16:04,554 basehttp "GET /static/rest_framework/docs/css/jquery.json-view.min.css HTTP/1.1" 200 1307
INFO 2025-03-14 16:16:04,559 basehttp "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2025-03-14 16:16:04,559 basehttp "GET /api/docs/schema.js HTTP/1.1" 200 3352
INFO 2025-03-14 16:16:04,559 basehttp "GET /static/rest_framework/css/bootstrap-theme.min.css HTTP/1.1" 200 23411
INFO 2025-03-14 16:16:04,561 basehttp "GET /static/rest_framework/css/font-awesome-4.0.3.css HTTP/1.1" 200 21658
INFO 2025-03-14 16:16:04,563 basehttp "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2025-03-14 16:16:04,565 basehttp "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
INFO 2025-03-14 16:16:04,566 basehttp "GET /static/rest_framework/docs/js/jquery.json-view.min.js HTTP/1.1" 200 2700
INFO 2025-03-14 16:16:04,566 basehttp "GET /static/rest_framework/docs/js/api.js HTTP/1.1" 200 10391
INFO 2025-03-14 16:16:04,566 basehttp "GET /static/rest_framework/js/coreapi-0.1.1.js HTTP/1.1" 200 157600
INFO 2025-03-14 16:16:04,568 basehttp "GET /static/rest_framework/docs/css/base.css HTTP/1.1" 200 6156
INFO 2025-03-14 16:16:04,619 basehttp "GET /static/rest_framework/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
INFO 2025-03-14 16:16:04,656 basehttp "GET /static/rest_framework/docs/img/favicon.ico HTTP/1.1" 200 5430
INFO 2025-03-14 16:23:11,383 basehttp "POST /api/account/logout/ HTTP/1.1" 200 32
WARNING 2025-03-14 16:28:15,608 log Unauthorized: /api/diary/2/like/
WARNING 2025-03-14 16:28:15,608 basehttp "POST /api/diary/2/like/ HTTP/1.1" 401 58
